### ISSUE TITLE
Нет городов

### ISSUE THREAD

**Issue by SoLowHigh** [melianmiko/ZeppOS-Transport#1]
Типа.. почему тут есть какие-то Пыть-Яхи, Свободные и Урюпински, но нет стандартных миллионников? Даже Москвы не нашёл) Мне лично Омск нужен

**Comment by melianmiko** [comment]
Приложение построено на базе сервиса bus62.ru, он же "Умный транспорт" для смартфонов (https://play.google.com/store/apps/details?id=ru.bus62.SmartTransport), и доступны в нём только те города, что и в указанном приложении.
